version: 0.0.1
metadata: null
config:
  check:
    purge: []
    deps:
      # essential packages
      - apt-transport-https
      - bash-completion
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - ffmpeg
      - flatpak
      - git
      - software-properties-common
      - ttf-mscorefonts-installer
      # pyenv dependencies
      - libbz2-dev
      - libffi-dev
      - liblzma-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxmlsec1-dev
      - tk-dev
      - xz-utils
      - zlib1g-dev
      # cargo-update dependencies
      - libgit2-dev
      - libssh-dev
      - libssl-dev
      - pkgconf
      # imagemagick dependencies
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      # docker dependencies
      - lsb-release
      # alacritty dependencies
      - libfontconfig1-dev
      - libfreetype6-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - pkg-config
    python:
      pyenvCheck: true
      version: 3.12
    rust:
      rustupCheck: true
      cargoUpdateCheck: true
  install:
    check: false
    apt:
      # CLI utils
      - fzf
      - gnupg2
      - openssh-server
      - stow
      - vim
      - xclip
      # apps
      - nautilus
      # multimedia
      - imagemagick
      - vlc
      # productivity
    ppa:
      - ppa: ppa:qbittorrent-team/qbittorrent-stable
        packages:
          - qbittorrent
      - name: ppa:obsproject/obs-studio
        packages:
          - obs-studio
    aptAltSourcesEnabled: false
    aptAltSources:
      - remoteGpgKey: https://packages.mozilla.org/apt/repo-signing-key.gpg
        gpgKeyPath: /etc/apt/keyrings/packages.mozilla.org.asc
        repo: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mo
        sourceFile: mozilla
        pinning: |-
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
        packages:
          - firefox
      - remoteGpgKey: https://download.docker.com/linux/ubuntu/gpg
        gpgKeyPath: /etc/apt/keyrings/docker.asc
        repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://downloa
        sourceFile: docker
        pinning: false
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      - remoteGpgKey: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
        gpgKeyPath: /usr/share/keyrings/vscodium-archive-keyring.gpg
        repo: deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.c
        sourceFile: vscodium
        pinning: false
        packages:
          - codium
      - remoteGpgKey: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        gpgKeyPath: /usr/share/keyrings/oracle-virtualbox-2016.asc
        repo: deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/oracle-virtualbox-2016.asc] https://download.virtualbox.org/virtualbox/debian $(. /etc/os-release && echo $UBUNTU_CODENAME) contrib
        sourceFile: virtualbox
        pinning: false
        packages:
          - virtualbox-7.0
    flatpak:
      - com.discordapp.Discord
      - com.obsproject.Studio
      - md.obsidian.Obsidian
      - org.gimp.GIMP
      - org.libreoffice.LibreOffice
      - org.telegram.desktop
    pip:
      - trash-cli
    cargoEnabled: false
    cargo:
      - alacritty
      - bat --locked
      - bottom --locked
      - du-dust
      - eza
      - starship --locked
      - zellij --locked
      - zoxide --locked
    appImage:
      - name: Bitwarden
        url: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=appimage
  update:
    check: true
    apt:
      apt: false
      aptFull: true # NOTE: apt must be true for aptFull to take effect
    flatpak: false
    pip: false
    cargo: false
    other:
      yq: true
      zellijClear: true
  configure:
    check: true
    stowMode: backup # override | backup
    dotfiles:
      - alacritty
      # - autostart
      - bash
      - codium
      - macchina
      - zellij
    theming:
      cinnamon: {}
