#!/bin/bash
# /usr/bin

set -euo pipefail

usage() {
  cat <<EOF
TIDES (The Idempotent Dev Environment Setup) is a post-install, update, & dotfile manager

Usage: tides [OPTIONS]

Commands:
  check         Installs dependencies, Python (via pyenv), Cargo (via rustup), & firmware packages
  install, i    Installs all packages. Auto-invokes \`configure\` when done
  update, u     Updates & upgrades apt, flatpak, cargo, pip packages
  configure, c  Dotfile manager (via Stow)
  help, h       Print help information

Configuration:
  Customise each command's behaviour by modifying the \`config.json\` file.
  Optionally, packages to be installed can be managed via \`deps.list\` & \`install.list\` text file.
  The config schema of $(config.json) is available at \`README.md\`.

Example:
  tides configure

EOF
}

error_msg() {
  cat <<EOF
Error: Invalid argument(s)

EOF
}

check() {
  echo check
}

install() {
  echo install
}

update() {
  inner() {
    varr="hihi"
    echo $varr
  }
  inner
}

configure() {
  echo configure
}

main() {
  [[ $# -gt 0 ]] || {
    usage
    error_msg
    exit 1
  }

  while [[ $# -gt 0 ]]; do
    case $1 in
      check)
        check
        ;;
      install | i)
        install
        ;;
      update | u)
        update
        ;;
      configure | c)
        configure
        ;;
      help | h)
        usage
        exit 0
        ;;
      *)
        usage
        error_msg
        exit 1
        ;;
    esac
    shift
  done
}

main "$@"
