#!/bin/bash
# /usr/bin

set -euo pipefail

if ! command -v jq &>/dev/null; then
  sudo apt-get update
  sudo apt-get install jq
fi

# ----- Apt -----

sudo apt-get update -qq
sudo apt-get upgrade -qy
if $(jq '.update.aptFull' config.json); then
  sudo apt-get autoclean -qqy
  sudo apt-get autoremove -qqy
fi

# ----- Flatpak -----
if $(jq '.update.flatpak' config.json) && command -v flatpak; then
  flatpak update -y
fi

# ----- Rust -----
if $(jq '.update.rust' config.json) && command -v rustup; then
  rustup update
  cargo install-update -a
fi
